"""empty message

Revision ID: 4496732b6718
Revises: 8546b81f57bb
Create Date: 2020-04-14 02:01:23.064622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4496732b6718'
down_revision = '8546b81f57bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('users', 'emailadress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emailadress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
